### ISSUE TITLE
Download NSI data

### ISSUE THREAD

**Issue by AbolfazlAnsari** [HydrologicEngineeringCenter/nsi-ui#45] opened 2022-09-07 22:31 UTC
Does anybody know when NSI data will be publicly available? I am doing my Ph.D. on the Susquehanna River's flood adaptation and need to access NSI data.

**Comment by trietmnj** [comment] 2022-09-08 13:36
Hi, we're in the final steps of deployment. I'm expecting the publicly accessible url to become available within the next few days, I can follow up with you here once it is up.

**Comment by HenryGeorgist** [comment] 2022-09-08 13:43
duplicate of #44

**Comment by trietmnj** [comment] 2022-09-21 15:30
Hi, I apologize for the delay. The data is available to download now. You can replace {statefips} in the link below with the fips number of the state you are trying to download.

https://nsi.sec.usace.army.mil/downloads/nsi_2022/nsi_2022_{statefips}.gpkg.zip

For reference, here is a list of states and their corresponding fips number. The data to the major 50 states and the District of Columbia should be available now.

https://www.mercercountypa.gov/dps/state_fips_code_listing.htm

As an example, the download link to Maryland should be:

https://nsi.sec.usace.army.mil/downloads/nsi_2022/nsi_2022_24.gpkg.zip

A web-map tool is also available to make downloading more intuitive, but it is not yet available on at a public url. I'm expecting the issue to be resolved relatively soon.

Please feel free to let us know if you run into any difficulty downloading the data.

**Comment by trietmnj** [comment] 2022-09-21 16:50
Update: the web-map tool is now available.

https://nsi.sec.usace.army.mil/downloads/

**Comment by HenryGeorgist** [comment] 2022-09-26 13:52
update - site down due to reverse proxy issue, eta for survice up 9/27

**Comment by HenryGeorgist** [comment] 2022-09-28 14:28
service restored on downloads

**Comment by HenryGeorgist** [comment] 2022-09-28 14:36
closing

**Closed as completed by HenryGeorgist** 2022-09-28 14:36 UTC
